import type {Database} from 'bun:sqlite';
import {readFileSync,statSync} from 'node:fs';
import {escapeHtml as e} from './newsletter.ts';

export type OwnerOptions={accountId?:string;analyticsFile?:string;releaseTag?:string;postalAddress?:string};
type Page=(title:string,content:string,script?:string,status?:number,language?:'en'|'ru')=>Response;
type Metric={source:string;metric:string;value:number;observed_at:string;dimensions:Record<string,string>};
type Snapshot={generated_at:string;latest:Metric[];event_daily:{day:string;source:string;kind:string;events:number}[];source_runs:{source:string;status:string;finished_at:string}[]};
export function ownerPortal(db:Database,page:Page,options:OwnerOptions){
 return (req:Request,account:{id:string;email:string}|null)=>{
  const url=new URL(req.url),ru=url.searchParams.get('lang')!=='en',lang=ru?'ru':'en',t=(en:string,ruText:string)=>ru?ruText:en;
  if(!account)return page(t('Sign in first','Сначала войдите'),`<p>${t('Use the Qoopia owner account.','Используйте аккаунт владельца Qoopia.')}</p><a href="/profile?lang=${lang}">${t('Open profile','Открыть профиль')}</a>`,'',401,lang);
  if(!options.accountId||account.id!==options.accountId)return page(t('Access unavailable','Нет доступа'),`<p>${t('This page is available only to the service owner.','Эта страница доступна только владельцу сервиса.')}</p>`,'',403,lang);
  if(req.method!=='GET'||url.pathname!=='/owner')return new Response(null,{status:404,headers:{'cache-control':'no-store'}});
  const date=(v:number|string|null)=>v?new Date(v).toLocaleString(ru?'ru-RU':'en-GB',{timeZone:'UTC'})+' UTC':t('Unknown (existing account)','Неизвестно (прежний аккаунт)');
  const count=(sql:string)=>(db.query(sql).get() as {n:number}).n;
  const pageNumber=Math.min(1000000,Math.max(0,Number.parseInt(url.searchParams.get('page')??'0',10)||0));
  const total=count('SELECT count(*) n FROM connection_accounts'),subscribers=count('SELECT count(*) n FROM news_preferences p JOIN connection_accounts a ON a.id=p.account_id AND a.email=p.email WHERE subscribed=1');
  const rows=db.query(`SELECT a.email,a.google_sub IS NOT NULL AS google,x.registered_at,x.last_login_at,x.login_count,COALESCE(p.subscribed,0) AS subscribed,p.email AS consent_email
   FROM connection_accounts a LEFT JOIN account_activity x ON x.account_id=a.id LEFT JOIN news_preferences p ON p.account_id=a.id ORDER BY a.id LIMIT 100 OFFSET ?`).all(pageNumber*100) as {email:string;google:number;registered_at:number|null;last_login_at:number|null;login_count:number|null;subscribed:number;consent_email:string|null}[];
  let snapshot:Snapshot|null=null;
  try{if(options.analyticsFile&&statSync(options.analyticsFile).size<5_000_000){const value=JSON.parse(readFileSync(options.analyticsFile,'utf8'));if(Number.isFinite(Date.parse(value.generated_at))&&Array.isArray(value.latest)&&Array.isArray(value.event_daily)&&Array.isArray(value.source_runs))snapshot=value;}}catch{/* Show unavailable; never present missing collection as zero. */}
  const stale=!snapshot||Date.now()-Date.parse(snapshot.generated_at)>900000||['github_releases','account_service','first_party_events'].some(name=>{const run=snapshot?.source_runs.find(r=>r.source===name);return !run||run.status!=='ok'||!Number.isFinite(Date.parse(run.finished_at))||Date.now()-Date.parse(run.finished_at)>900000;});
  const downloads=(snapshot?.latest??[]).filter(r=>r.source==='github_releases'&&r.metric==='asset_downloads'&&r.dimensions?.tag===options.releaseTag&&/\.(dmg|tar\.gz)$/.test(r.dimensions.file??''));
  const events=(snapshot?.event_daily??[]).filter(r=>r.source==='server'&&['auth_request','email_confirmed','profile_login','profile_logout','mail_accepted','mail_failed'].includes(r.kind)).slice(0,90);
  const eventNames:Record<string,string>={auth_request:t('Sign-in requests','Запросы входа'),email_confirmed:t('Email confirmations','Подтверждения почты'),profile_login:t('Profile sign-ins','Входы в профиль'),profile_logout:t('Sign-outs','Выходы'),mail_accepted:t('Emails accepted by provider','Письма приняты провайдером'),mail_failed:t('Email send errors','Ошибки отправки писем')};
  const table=(head:string[],body:string[][])=>`${head.length>3?`<p class="owner-scroll">${t('Scroll the table sideways to see all columns.','Прокрутите таблицу вбок, чтобы увидеть все столбцы.')}</p>`:''}<div class="owner-table" tabindex="0" role="region" aria-label="${e(head.join(', '))}"><table><thead><tr>${head.map(v=>`<th scope="col">${e(v)}</th>`).join('')}</tr></thead><tbody>${body.map(row=>`<tr>${row.map(v=>`<td><!--email_off-->${e(v)}<!--/email_off--></td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const deliveries=db.query('SELECT c.subject,d.status,count(*) AS n FROM news_deliveries d JOIN news_campaigns c ON c.id=d.campaign_id GROUP BY c.id,d.status ORDER BY c.created_at DESC LIMIT 50').all() as {subject:string;status:string;n:number}[];
  const statuses:Record<string,string>={sending:t('Outcome needs checking','Результат требует проверки'),accepted:t('Accepted by provider','Принято провайдером'),failed:t('Rejected by provider','Отказ провайдера'),uncertain:t('Outcome unknown','Результат неизвестен'),skipped:t('Subscription changed; skipped','Подписка изменена; пропущено')};
  return page(t('Owner dashboard','Панель владельца'),`<section class="q-owner"><nav class="profile-nav"><a href="/profile?lang=${lang}">${t('Back to profile','Вернуться в профиль')}</a><a href="/owner?lang=${ru?'en':'ru'}">${ru?'English':'Русский'}</a></nav>
   <p>${t('Accounts update immediately. Downloads and events update about every five minutes.','Аккаунты обновляются сразу. Скачивания и события — примерно раз в пять минут.')}</p>
   <dl class="owner-totals"><div><dt>${t('Accounts','Аккаунты')}</dt><dd>${total}</dd></div><div><dt>${t('News subscribers','Подписчики новостей')}</dt><dd>${subscribers}</dd></div><div><dt>${t('Profiles with valid sessions','Профили с действующей сессией')}</dt><dd>${count('SELECT count(DISTINCT account_id) n FROM profile_sessions WHERE expires>'+Date.now())}</dd></div></dl>
   <p class="owner-freshness" role="status">${stale?t('Collection unavailable or stale. Values below may be outdated.','Сбор недоступен или устарел. Значения ниже могут быть неактуальны.'):t('Collection is up to date.','Данные свежие.')} ${snapshot?e(date(snapshot.generated_at)):''}</p><a class="btn deny" href="/owner?lang=${lang}&page=${pageNumber}">${t('Refresh','Обновить')}</a>
   <section><h2>${t('Installer downloads','Скачивания установщиков')}</h2>${downloads.length?table([t('Platform','Платформа'),t('File downloads','Загрузок файла'),t('Observed','Проверено')],downloads.map(r=>[r.dimensions.file?.endsWith('.dmg')?'macOS Apple Silicon':'Linux x64',String(r.value),date(r.observed_at)])):`<p>${t('Download counts are not available yet.','Счётчики скачиваний пока недоступны.')}</p>`}<p>${t('File downloads include retries and automation. They do not count people or completed installations. Two release verification downloads are recorded separately.','Счётчики включают повторы и автоматизацию. Это не количество людей или завершённых установок. Две контрольные загрузки релиза отмечены отдельно.')}</p></section>
   <section><h2>${t('Accounts','Аккаунты')}</h2><p>${t('Private account data. Existing accounts have no reconstructed registration date. Counters start when this feature is enabled; a valid session does not mean someone is online.','Закрытые данные аккаунтов. Даты регистрации прежних аккаунтов не восстановлены. Счётчики входов начинаются с включения этой функции; действующая сессия не означает, что человек сейчас онлайн.')}</p>${table([t('Email','Почта'),t('Registered','Регистрация'),t('Last sign-in','Последний вход'),t('Sign-ins','Входов'),t('News','Новости')],rows.map(r=>[r.email,date(r.registered_at),r.last_login_at?date(r.last_login_at):t('Not recorded yet','Пока не зафиксирован'),String(r.login_count??0),r.subscribed&&r.consent_email===r.email?t('Subscribed','Подписан'):t('Not subscribed','Не подписан')]))}<nav class="owner-pagination" aria-label="${t('Account pages','Страницы аккаунтов')}">${pageNumber>0?`<a href="?lang=${lang}&page=${pageNumber-1}">${t('Previous','Назад')}</a>`:''}<span>${t('Page','Страница')} ${pageNumber+1}</span>${(pageNumber+1)*100<total?`<a href="?lang=${lang}&page=${pageNumber+1}">${t('Next','Далее')}</a>`:''}</nav></section>
   <section><h2>${t('Sign-ins and service emails','Входы и служебные письма')}</h2><p>${t('UTC days. Includes operational checks. Provider acceptance does not confirm inbox delivery or reading.','Дни по UTC. Включает технические проверки. Принятие провайдером не подтверждает доставку в ящик или прочтение.')}</p>${events.length?table([t('Day','День'),t('Event','Событие'),t('Count','Количество')],events.map(r=>[r.day,eventNames[r.kind]??r.kind,String(r.events)])):`<p>${t('No event data is available.','Данные событий пока недоступны.')}</p>`}</section>
   <section><h2>${t('Newsletters','Рассылки')}</h2><p>${options.postalAddress?t('Sender details are configured. Campaigns require an explicit operator send command.','Реквизиты отправителя настроены. Каждая рассылка запускается отдельной явной командой оператора.'):t('Sending is disabled until the public postal address of the sender is configured. Subscriptions and unsubscribe work.','Отправка выключена до настройки публичного почтового адреса отправителя. Подписка и отписка работают.')}</p>${deliveries.length?table([t('Subject','Тема'),t('Status','Состояние'),t('Count','Количество')],deliveries.map(r=>[r.subject,statuses[r.status]??r.status,String(r.n)])):`<p>${t('No newsletters have been sent.','Новостные письма ещё не отправлялись.')}</p>`}</section>
   <details><summary>${t('Collection sources','Источники сбора')}</summary>${snapshot?table([t('Source','Источник'),t('Status','Состояние'),t('Updated','Обновлено')],snapshot.source_runs.map(r=>[r.source,r.status,date(r.finished_at)])):t('Unavailable','Недоступно')}</details>
   </section>`,'',200,lang);
 };
}
