import {newsConsent} from './newsletter.ts';
const escape=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Page=(title:string,content:string,script?:string,status?:number,language?:'en'|'ru')=>Response;

export function profileView(page:Page,ru:boolean,account:{email:string;url:string|null}|null,suggested:string,pending:boolean,options:{subscribed?:boolean;owner?:boolean}={}) {
  const t=(en:string,ruText:string)=>ru?ruText:en,lang=ru?'ru':'en';
  const languageLink='/profile?lang='+(ru?'en':'ru')+(suggested?'&dashboard='+encodeURIComponent(suggested):'');
  const address=account?.url??suggested;
  const content=`<section class="q-profile">
    <nav class="profile-nav" aria-label="${t('Profile navigation','Навигация профиля')}"><a href="https://qoopia.ai/?lang=${lang}">← ${t('Website','На сайт')}</a><a href="${escape(languageLink)}" lang="${ru?'en':'ru'}">${ru?'English':'Русский'}</a></nav>
    ${account?`<div class="profile-identity"><div><span class="profile-caption">${t('YOUR ACCOUNT · EMAIL CONFIRMED','ВАШ АККАУНТ · ПОЧТА ПОДТВЕРЖДЕНА')}</span><p class="profile-email" id="profile-email"><!--email_off-->${escape(account.email)}<!--/email_off--></p></div><button class="deny" id="signout">${t('Sign out','Выйти')}</button></div>
    <div class="profile-grid"><article class="profile-panel"><span class="profile-caption">01 / ${t('YOUR MEMORY','ВАША ПАМЯТЬ')}</span><h2>${t('My dashboard','Мой дашборд')}</h2>
      ${account.url?`<p>${t('Your saved Qoopia address. Sign in there with the account linked to that workspace.','Сохранённый адрес вашей Qoopia. Войдите там под аккаунтом, связанным с этим пространством.')}</p><a class="btn profile-primary" id="open-dashboard" href="${escape(account.url)}" rel="noreferrer">${t('Open dashboard','Открыть дашборд')} ↗</a><p class="profile-address">${escape(account.url)}</p><p class="profile-small">${t('Your computer or server must be running. A localhost address opens only on that same computer.','Компьютер или сервер должен работать. Адрес localhost открывается только на том же компьютере.')}</p>`:
      `<p class="profile-lead">${t('Your account is ready. Add the address of your existing dashboard, or set up Qoopia first.','Аккаунт готов. Добавьте адрес существующего дашборда или сначала настройте Qoopia.')}</p><p>${t('Signing in to this website does not create a memory database. Your dashboard lives in your Qoopia installation.','Вход на сайт не создаёт базу памяти. Дашборд находится в вашей установленной Qoopia.')}</p>`}
      <p id="profile-status" role="status" aria-live="polite" tabindex="-1"></p><details ${account.url?'':'open'}><summary>${t('Save a dashboard address','Сохранить адрес дашборда')}</summary><form id="dashboard-form"><label for="dashboard-url">${t('Address from your Qoopia browser window','Адрес из окна вашей Qoopia в браузере')}</label><input id="dashboard-url" name="dashboard" autocomplete="off" spellcheck="false" type="url" maxlength="512" value="${escape(address)}" placeholder="https://your-server.example/dashboard" required aria-describedby="address-help"><p id="address-help" class="profile-small">${t('Open Qoopia, copy the dashboard address and save it here. This saves a shortcut; access is still checked by your installation. Use the dashboard address, not the agent connection address.','Откройте Qoopia, скопируйте адрес дашборда и сохраните здесь. Сохранится ссылка; права доступа по-прежнему проверяет ваша установка. Нужен адрес дашборда, а не подключения агента.')}</p><div class="actions"><button type="submit">${t('Save address','Сохранить адрес')}</button>${account.url?`<button type="button" class="deny" id="remove-dashboard">${t('Remove shortcut','Убрать ссылку')}</button>`:''}</div></form></details>
    </article><aside class="profile-panel profile-quiet"><span class="profile-caption">02 / ${t('FIRST TIME HERE?','ВПЕРВЫЕ ЗДЕСЬ?')}</span><h2>${t('Open your Qoopia','Откройте свою Qoopia')}</h2><ol class="profile-steps"><li><strong>${t('Already installed','Уже установлена')}</strong><p>${t('On Mac, open Qoopia from Applications. On Linux, open Qoopia from the application menu, or run qoopia open. It opens your selected dashboard.','На Mac откройте Qoopia в «Программах». На Linux — в меню приложений или командой qoopia open. Откроется выбранный дашборд.')}</p></li><li><strong>${t('Using your own server','Есть свой сервер')}</strong><p>${t('Save its dashboard address on this page. Use the email already linked to that workspace when signing in there.','Сохраните адрес его дашборда на этой странице. При входе используйте почту, уже связанную с этим пространством.')}</p></li><li><strong>${t('No installation yet','Ещё не установлена')}</strong><p>${t('Install Qoopia and complete the first sign-in. Your dashboard opens when setup is complete. Downloading the file alone does not create it.','Установите Qoopia и завершите первый вход. Дашборд откроется после настройки. Одного скачивания файла недостаточно.')}</p><a href="https://qoopia.ai/?lang=${lang}#download">${t('Download Qoopia','Скачать Qoopia')} ↗</a></li></ol></aside></div>`:
    `<div class="profile-grid"><div><span class="profile-caption">${t('YOUR ACCOUNT. YOUR WAY BACK.','ВАШ АККАУНТ. ПУТЬ К СВОЕЙ ПАМЯТИ.')}</span><p class="profile-lead">${t('Your email and your dashboard, in one place.','Ваша почта и ваш дашборд — в одном месте.')}</p><p>${t('Use the same email you used in Qoopia. If you are new, confirming your email creates your profile.','Используйте ту же почту, с которой входили в Qoopia. Если вы здесь впервые, подтверждение почты создаст профиль.')}</p><p>${t('A profile is available before installation. Your memory dashboard becomes available after setting up Qoopia on a computer or connecting your own server.','Профиль доступен до установки. Дашборд памяти появляется после настройки Qoopia на компьютере или подключения своего сервера.')}</p><a href="https://qoopia.ai/docs.html?lang=${lang}#dashboard">${t('How to open your dashboard','Как открыть свой дашборд')} ↗</a></div><div class="profile-panel"><p id="profile-status" role="status" aria-live="polite" tabindex="-1"></p><form id="signin-form"><label for="email">${t('Your email','Ваша почта')}</label><input id="email" name="email" spellcheck="false" type="email" autocomplete="email" required maxlength="254" placeholder="you@example.com"><label class="news-choice"><input id="signup-news" type="checkbox"><span>${newsConsent[lang]}</span></label><button class="profile-primary" type="submit">${t('Continue with email','Продолжить с почтой')}</button></form><div class="profile-divider">${t('or','или')}</div><button class="deny profile-primary" id="google">${t('Continue with Google','Продолжить с Google')}</button><p class="profile-small">${t('We will send a confirmation link. No password to remember.','Отправим ссылку для подтверждения. Запоминать пароль не нужно.')}</p><a class="btn profile-primary" id="google-link" hidden target="_blank" rel="noopener noreferrer">${t('Choose Google account','Выбрать аккаунт Google')} ↗</a><button class="deny profile-primary" id="check" ${pending?'':'hidden'}>${t('Check sign-in','Проверить вход')}</button><p class="profile-small">${t('An app sign-in and a website sign-in are separate sessions. You may need to confirm your email once in this browser.','Вход в приложение и вход на сайт — отдельные сессии. В этом браузере может потребоваться один раз подтвердить почту.')}</p></div></div>`}
    ${account?`<section class="profile-news" aria-labelledby="news-heading"><h2 id="news-heading">${t('News from Qoopia','Новости Qoopia')}</h2><form id="news-form"><label class="news-choice"><input id="news-optin" type="checkbox" ${options.subscribed?'checked':''}><span>${newsConsent[lang]}</span></label><button type="submit">${t('Save preference','Сохранить выбор')}</button><p id="news-status" role="status" aria-live="polite"></p></form></section>${options.owner?`<p><a class="btn deny" href="/owner?lang=${lang}">${t('Open owner dashboard','Панель владельца')}</a></p>`:''}`:''}
    <footer class="profile-footer"><span>${t('Your memory stays on your computer or server.','Ваша память остаётся на вашем компьютере или сервере.')}</span><a href="/privacy">${t('Privacy','Конфиденциальность')}</a></footer>
  </section>`;
  const messages={sending:t('Preparing sign-in…','Подготавливаем вход…'),google:t('Choose your Google account using the button below. Then confirm the email we send and return here.','Выберите аккаунт Google кнопкой ниже. Затем подтвердите письмо, которое мы отправим, и вернитесь сюда.'),sent:t('Check your email, confirm the link, then return here. This page will continue automatically.','Откройте письмо, подтвердите ссылку и вернитесь сюда. Эта страница продолжит вход автоматически.'),waiting:t('Complete the account confirmation, then return here.','Завершите подтверждение аккаунта и вернитесь сюда.'),failed:t('Could not complete the action. Please try again.','Не удалось завершить действие. Попробуйте ещё раз.'),expired:t('Sign-in expired. Request a new link.','Время входа истекло. Запросите новую ссылку.'),invalid:t('Use your dashboard URL: HTTPS for a server, or HTTP localhost on your computer. Do not use an MCP address or a link containing a token.','Укажите адрес дашборда: HTTPS для сервера или HTTP localhost на своём компьютере. Не используйте адрес MCP или ссылку с токеном.'),limit:t('Too many attempts. Please try again later.','Слишком много попыток. Попробуйте позже.'),conflict:t('These login details belong to different accounts. Sign in with the original email.','Эти данные входа связаны с разными аккаунтами. Используйте исходную почту.')};
  return page(t('Profile','Профиль'),content,`
    document.documentElement.lang=${JSON.stringify(lang)};
    const M=${JSON.stringify(messages)},status=document.querySelector('#profile-status');let timer,deadline=Date.now()+600000,polling=false;
    const show=e=>{status.textContent=Object.values(M).includes(e.message)?e.message:M.failed;status.focus();};
    async function post(path,body={}){const r=await fetch('/profile/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw new Error(d.error==='INVALID_DASHBOARD'?M.invalid:d.error==='ACCOUNT_CONFLICT'?M.conflict:r.status===410||r.status===401?M.expired:r.status===429?M.limit:M.failed);return d;}
    async function poll(){if(polling)return;clearTimeout(timer);polling=true;try{const d=await post('poll');if(d.ok){location.reload();return;}status.textContent=M.waiting;if(Date.now()<deadline)timer=setTimeout(poll,4000);else status.textContent=M.expired;}catch(e){show(e);}finally{polling=false;}}
    const form=document.querySelector('#signin-form'),google=document.querySelector('#google');
    async function start(method){if(method==='email'&&!form.reportValidity())return;clearTimeout(timer);form.querySelector('button').disabled=true;google.disabled=true;status.textContent=M.sending;try{const d=await post('start',{method,language:${JSON.stringify(lang)},news:document.querySelector('#signup-news').checked,email:document.querySelector('#email').value.trim()});const a=document.querySelector('#google-link');a.hidden=!d.google_url;if(d.google_url)a.href=d.google_url;status.textContent=d.google_url?M.google:M.sent;if(d.google_url)a.focus();document.querySelector('#check').hidden=false;deadline=Date.now()+600000;timer=setTimeout(poll,4000);}catch(e){show(e);}finally{form.querySelector('button').disabled=false;google.disabled=false;}}
    if(form){form.onsubmit=e=>{e.preventDefault();start('email');};google.onclick=()=>start('google');document.querySelector('#check').onclick=poll;${pending?'timer=setTimeout(poll,4000);':''}}
    const saved=document.querySelector('#dashboard-form');if(saved)saved.onsubmit=async e=>{e.preventDefault();const button=saved.querySelector('button');button.disabled=true;try{await post('dashboard',{url:document.querySelector('#dashboard-url').value.trim()});location.href='/profile?lang=${lang}';}catch(e){show(e);button.disabled=false;}};
    for(const [id,path,body] of [['signout','logout',{}],['remove-dashboard','dashboard',{url:null}]]){const b=document.getElementById(id);if(b)b.onclick=async()=>{b.disabled=true;try{await post(path,body);location.href='/profile?lang=${lang}';}catch(e){show(e);b.disabled=false;}};}
    const newsForm=document.querySelector('#news-form');if(newsForm)newsForm.onsubmit=async e=>{e.preventDefault();const button=newsForm.querySelector('button'),note=document.querySelector('#news-status');button.disabled=true;note.textContent='${t('Saving…','Сохраняем…')}';try{await post('news',{subscribed:document.querySelector('#news-optin').checked,language:'${lang}'});note.textContent='${t('Your choice is saved.','Ваш выбор сохранён.')}';}catch(e){note.textContent=e.message;}finally{button.disabled=false;}};
    addEventListener('pagehide' ,()=>clearTimeout(timer));
  `,200,lang);
}
