#!/usr/bin/env bun
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { spawn, spawnSync } from "node:child_process";
import { existsSync, readFileSync, statfsSync, writeFileSync } from "node:fs";
import { totalmem } from "node:os";
import { dirname, join, resolve } from "node:path";

const MiB = 1024 ** 2, GiB = 1024 ** 3, EXPECTED_MANIFEST = "911808dd92f7fdc4c2ada615bb1e3fad211b302dd05d272a447819e9ed11c4d3", EXPECTED_BINARY = "9b12891219818ab3c0c609fdc841e60001ba9b5302c59357cd42b3c403655e0b";
const args = process.argv.slice(2), value = (name: string) => { const i=args.indexOf(`--${name}`); if(i<0||!args[i+1])throw new Error(`--${name} required`); return args[i+1]!; };
const size = Number(value("bytes")), target=resolve(value("target")), bundle=resolve(value("bundle")), driver=resolve(value("driver"));
assert([256*MiB,GiB].includes(size),"REFUSED_MEASUREMENT_BYTES");
assert(!existsSync(target),"REFUSED_TARGET_EXISTS");
const sha=(file:string)=>createHash("sha256").update(readFileSync(file)).digest("hex"), manifestFile=join(bundle,"manifest.json"), binaryFile=join(bundle,"qoopia");
assert.equal(sha(manifestFile),EXPECTED_MANIFEST,"REFUSED_MANIFEST_IDENTITY_MISMATCH"); assert.equal(sha(binaryFile),EXPECTED_BINARY,"REFUSED_BINARY_IDENTITY_MISMATCH");
const manifest=JSON.parse(readFileSync(manifestFile,"utf8")) as {source_digest:string;members:Record<string,{size:number;sha256:string}>}; let members=0,bundleBytes=0;
for(const [name,spec] of Object.entries(manifest.members)){const file=join(bundle,name);assert.equal(sha(file),spec.sha256,name);assert.equal(readFileSync(file).byteLength,spec.size,name);members++;bundleBytes+=spec.size;} assert.equal(members,63);
const run=(file:string,a:string[])=>spawnSync(file,a,{encoding:"utf8"}).stdout.trim();
const pressure=()=>{const text=run("/usr/bin/memory_pressure",["-Q"]),m=text.match(/System-wide memory free percentage:\s*(\d+)%/);if(!m)throw new Error(`MEMORY_PRESSURE_UNREADABLE: ${text}`);return {free_percent:Number(m[1]),raw:text};};
const swap=()=>{const text=run("/usr/sbin/sysctl",["-n","vm.swapusage"]),m=text.match(/used = ([0-9.]+)([MG])/);if(!m)throw new Error(`SWAP_UNREADABLE: ${text}`);return {used_bytes:Number(m[1])*(m[2]==="G"?GiB:MiB),raw:text};};
const disk=()=>{const s=statfsSync(dirname(target));return s.bavail*s.bsize;}, p0=pressure(), s0=swap(), d0=disk(), liveAvailable=Math.floor(totalmem()*p0.free_percent/100), streamedRuntimeBound=size===256*MiB?512*MiB:GiB, safetyReserve=GiB, memoryRequired=streamedRuntimeBound+safetyReserve, diskRequired=6*size+2*bundleBytes+GiB;
const minimumFreePercent=size===256*MiB?40:50;assert(liveAvailable>=memoryRequired,`REFUSED_LIVE_AVAILABLE_MEMORY: required=${memoryRequired} available=${liveAvailable}`); assert(p0.free_percent>=minimumFreePercent,`REFUSED_MEMORY_PRESSURE_HEADROOM: required_percent=${minimumFreePercent} free_percent=${p0.free_percent}`); assert(d0>=diskRequired,`REFUSED_INSUFFICIENT_DISK: required=${diskRequired} available=${d0}`);
const state=join(target,"measurement-state.json"), stdout=join(dirname(target),`${target.split("/").at(-1)}-stdout.log`), stderr=join(dirname(target),`${target.split("/").at(-1)}-stderr.log`), started=Date.now();
const child=spawn(process.execPath,[driver,"--recovery-scale","--execution-mode","sanctioned-guest-scale","--allow-test-fixture","--allow-streaming-measurement","--bundle",bundle,"--manifest-sha256",EXPECTED_MANIFEST,"--binary-sha256",EXPECTED_BINARY,"--target",target,"--measurement-bytes",String(size),"--measurement-state",state],{detached:true,stdio:["ignore","pipe","pipe"],env:{PATH:"/usr/bin:/bin",HOME:process.env.HOME!,TMPDIR:"/private/tmp"}});
let out="",err="";child.stdout!.on("data",b=>out+=b);child.stderr!.on("data",b=>err+=b);
type Metric={started_ms:number;ended_ms:number;peak_tree_rss_bytes:number;disk_before_bytes:number;disk_min_bytes:number;disk_after_bytes?:number;samples:number};
const phases:Record<string,Metric>={}, samples:Array<Record<string,unknown>>=[];let current="startup",danger="",peak=0,minDisk=d0,lastSample=started;
const stop=()=>{try{process.kill(-child.pid!,"SIGTERM");}catch{} setTimeout(()=>{try{process.kill(-child.pid!,"SIGKILL");}catch{}},3000);};
const tick=()=>{const now=Date.now();if(existsSync(state)){try{const p=JSON.parse(readFileSync(state,"utf8")).phase as string;if(p!==current){if(phases[current])phases[current]!.ended_ms=now-started;current=p;}}catch{}}
 const ps=run("/bin/ps",["-axo","pid=,ppid=,rss="]), rows=ps.split("\n").map(x=>x.trim().split(/\s+/).map(Number)).filter(x=>x.length===3), owned=new Set<number>([child.pid!]);let changed=true;while(changed){changed=false;for(const [pid,ppid] of rows)if(owned.has(ppid!)&&!owned.has(pid!)){owned.add(pid!);changed=true;}} const rss=rows.filter(([pid])=>owned.has(pid!)).reduce((n,r)=>n+r[2]!*1024,0), p=pressure(),s=swap(),d=disk();peak=Math.max(peak,rss);minDisk=Math.min(minDisk,d);
 const metric=phases[current]??={started_ms:now-started,ended_ms:now-started,peak_tree_rss_bytes:0,disk_before_bytes:d,disk_min_bytes:d,samples:0};metric.ended_ms=now-started;metric.peak_tree_rss_bytes=Math.max(metric.peak_tree_rss_bytes,rss);metric.disk_min_bytes=Math.min(metric.disk_min_bytes,d);metric.samples++;phases[current]=metric;samples.push({at_ms:now-started,phase:current,tree_rss_bytes:rss,processes:owned.size,disk_free_bytes:d,memory_free_percent:p.free_percent,swap_used_bytes:s.used_bytes});lastSample=now;
 if(p.free_percent<20)danger=`STOP_MEMORY_PRESSURE_${p.free_percent}`;else if(s.used_bytes-s0.used_bytes>64*MiB)danger=`STOP_SWAP_GROWTH_${s.used_bytes-s0.used_bytes}`;else if(d<GiB)danger=`STOP_DISK_RESERVE_${d}`;else if(now-started>480000)danger="STOP_TOTAL_TIMEOUT_480000";if(danger)stop();};
const timer=setInterval(tick,500);tick();
const exitCode:number=await new Promise(resolve=>child.on("close",code=>resolve(code??-1)));clearInterval(timer);if(Date.now()-lastSample>250)tick();writeFileSync(stdout,out,{mode:0o600});writeFileSync(stderr,err,{mode:0o600});
const d1=disk(),p1=pressure(),s1=swap();for(const metric of Object.values(phases))metric.disk_after_bytes=d1;
const report={format:"qoopia-p3-recovery-streaming-measurement/1",status:exitCode===0&&!danger?"PASS":"STOPPED_OR_FAILED",bytes:size,target,driver_sha256:sha(driver),bundle:{manifest_sha256:EXPECTED_MANIFEST,binary_sha256:EXPECTED_BINARY,source_digest:manifest.source_digest,members_verified:members},preflight:{physical_memory_bytes:totalmem(),memory_free_percent:p0.free_percent,minimum_free_percent:minimumFreePercent,estimated_available_memory_bytes:liveAvailable,memory_required_bytes:memoryRequired,memory_formula:`${streamedRuntimeBound} byte streamed runtime bound + ${safetyReserve} byte safety reserve`,disk_available_bytes:d0,disk_required_bytes:diskRequired,swap:s0.raw},guard:{total_timeout_ms:480000,stop_memory_free_percent_below:20,stop_swap_growth_bytes:64*MiB,stop_disk_free_bytes_below:GiB},result:{exit_code:exitCode,danger,elapsed_ms:Date.now()-started,peak_process_tree_rss_bytes:peak,disk_before_bytes:d0,disk_peak_consumption_bytes:d0-minDisk,disk_after_bytes:d1,memory_free_percent_after:p1.free_percent,swap_after:s1.raw,phases},logs:{stdout,stderr},samples};
const reportFile=join(target,"measurement-supervisor.json");writeFileSync(reportFile,JSON.stringify(report,null,2)+"\n",{mode:0o600});console.log(JSON.stringify({...report,samples:undefined,report_file:reportFile},null,2));if(report.status!=="PASS")process.exit(2);
